name: 1

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted 
    timeout-minutes: 9999

    steps:
    - name: Mendownload Ngrok.
      run: |
        docker run -p 6070:80 dorowu/ubuntu-desktop-lxde-vnc
